@extends('Layouts.userlayout')
@section('navbar')
@include('partials.navbar')
@endsection
@section('header')
@include('partials.header')
@endsection
@section('about')
@include('partials.aboutme')
@endsection
@section('services')
@include('partials.services')
@endsection
@section('projects')
@include('partials.projects')
@endsection
@section('testimonials')
@include('partials.testimonials')
@endsection
@section('contact')
@include('partials.contact')
@endsection
@section('blog')
@include('partials.blog')
@endsection
@section('footer')
@include('partials.footer')
@endsection